# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# Commands and Apps to be executed at launch
exec-once = clash-verge
#exec-once = dispwin ~/.local/share/color/icc/nv140fhm_n62.icc
#exec-once = hyprpaper

