# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #F4E5D1
background         #161415
cursor             #8E8A91

active_tab_foreground     #161415
active_tab_background     #F4E5D1
inactive_tab_foreground   #F4E5D1
inactive_tab_background   #161415

active_border_color   #F4E5D1
inactive_border_color #161415
bell_border_color     #130E10

color0      #3D3C3C
color1		#130E10
color2		#1D243E
color3		#37251E
color4		#704831
color5		#2D5486
color6		#A8875C
color7		#E7D1B4
color8		#A2927E
color9		#191316
color10		#273052
color11		#493128
color12		#956041
color13		#3C70B2
color14		#E0B47B
color15		#E7D1B4
